### ISSUE TITLE
Discrepancy between source advisory file and osv.dev

### ISSUE THREAD

**Issue by xaldama** [google/osv.dev#1002]
I am comparing the content of the source advisory file GHSA-2cxf-6567-7pp6.json from github advisory database and the one in google ovs.dev and there is one important difference.

**Source file**
https://github.com/github/advisory-database/blob/b4fb55f2669be0216baf4cfb9a01fe4533007957/advisories/github-reviewed/2021/03/GHSA-2cxf-6567-7pp6/GHSA-2cxf-6567-7pp6.json

**OSV File**
https://osv.dev/vulnerability/GHSA-2cxf-6567-7pp6

The original file does not have "Affected versions" data and it is added into ovs.dev file. 
This "Affected versions" information is not correct.

Where is this data added?
How can it be fixed?

**Comment by oliverchang** [comment]
Hi, thanks for the question! 

We add "affected versions" as a data improvement by expanding the provided version ranges from the source. 

In this case, the source has:

```json
            {
              "introduced": "0"
            },
            {
              "fixed": "1.0.0-beta.9"
            }
```

So we expand it into individual versions as part of "affected versions".

As you pointed out, there's some weirdness here in that "1.0.0-beta10" and "1.0.0-beta11" are included here.

This is because "1.0.0-beta10" and "1.0.0-beta11" both actually sort **before** "1.0.0-beta.9" according to [Maven's version ordering rules ](https://maven.apache.org/pom.html#Dependency_Version_Requirement_Specification)

Specifically, these strange rules:

> A transition between digits and characters is equivalent to a hyphen. 

> else ".qualifier" = "-qualifier" < "-number" < ".number"

In this case specifically, it looks like the advisory intends to exclude "1.0.0-beta10" and "1.0.0-beta11", so we can fix this at the source by editing the introduced to start from [1.0.0-beta.6](https://deps.dev/maven/com.datadoghq%3Adatadog-api-client/2.7.0/versions) instead.

**Comment by oliverchang** [comment]
I've submitted https://github.com/github/advisory-database/pull/1656 to fix this.

**Comment by oliverchang** [comment]
https://osv.dev/vulnerability/GHSA-2cxf-6567-7pp6 is now fixed since the GHSA PR has been merged. Thanks agai nfor reporting this!

**Comment by xaldama** [comment]
Thanks you!
