### ISSUE TITLE
Don't suggest using -X POST

### ISSUE THREAD

**Issue by dfandrich** [google/osv.dev#1081]
On https://osv.dev/#use-the-api is the instruction
```
Query by commit hash

curl -X POST -d \
  '{"commit": "6879efc2c1596d11a6a6ad296f80063b558d5e0f"}' \
  "https://api.osv.dev/v1/query"
```

Using `-X POST` here is unnecessary, redundant and potentially dangerous as people cut and paste this into more places. curl will actually tell you this if you add `-v` to this command:

`Note: Unnecessary use of -X or --request, POST is already inferred.`

See also https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

**Comment by andrewpollock** [comment]
Thanks @dfandrich for bringing this to our attention!

**Comment by andrewpollock** [comment]
This issue is also applicable at https://github.com/google/osv.dev#using-the-api

**Comment by andrewpollock** [comment]
> See also https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

I should have read the actual blog post _before_ our awesome tech writer cranked out a PR in short order.

The comments on the blog post are somewhat illuminating of usability/discoverability problems with curl's command line flags. It's no longer anywhere near as self-evident to a casual reader of our documentation that the API is using HTTP POST methods, not GET ones. 

I'm not sure that this lack of clarity serves our users particularly well...

I'm now left wondering if `wget --post-data` is more fit-for-purpose than `curl --data`? (I'm so old school I remember the time when `wget` was called `geturl` and so it's my goto CLI for HTTP due to decades of muscle memory).

Data from Debian (again, I'm old school), seems to suggest that its reporting user base has more `wget` installed than `curl`:

https://qa.debian.org/popcon.php?package=curl
versus
https://qa.debian.org/popcon.php?package=wget

So based on one data point, and subjectively better conveyance of the HTTP method required to interact with the API, maybe we should switch all references to `wget` instead?

@oliverchang do you have any particular feelings?

**Comment by andrewpollock** [comment]
Colleagues have pointed out a good reason to stick with `curl` is it's installed on Mac OS by default, whereas `wget` is not.

**Comment by andrewpollock** [comment]
![analytics google com_analytics_web_](https://user-images.githubusercontent.com/6906046/222324335-9444e5b7-c7e9-4645-a2e5-529c37e9ffaf.png)

Data driven decision making ftw!
