### ISSUE TITLE
Problems utilising Debian purls

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#1321]
I have also noticed an issue regarding debian purls, if you add distro to the purl then from what i've seen it is ignored, also arch=source is problematic as it automatically disqualifies querying by a specific architecture i.e. x86
example: 
    "package": {
        "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?distro=debian-8"
    }
will ignore the distro query and return the vulnerabilities
and querying 
    "package": {
        "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64"
    }
will result with empty object, querying with arch=any also yields empty result.
this is the purl returned by osv
![image](https://github.com/google/osv.dev/assets/38865738/595e7e7e-20be-4f0f-946b-2d32bdaacbc9)
purl spec for reference https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst

_Originally posted by @satanshiro in https://github.com/google/osv.dev/issues/1234#issuecomment-1559112256_

**Comment by andrewpollock** [comment]
@satanshiro is it fair to say this is more of an issue when trying to search using a purl with the API?

Ideally you'd like the search for using

```
"package": {
  "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64"
}
```

to match vulnerabilities that have `pkg:deb/debian/imagemagick?arch=source`?

and

```
"package": {
  "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?distro=debian-8"
}
```

to only match vulnerabilities in what is essentially the `Debian:8` ecosystem?

**Comment by satanshiro** [comment]
To be honest I'm not sure I can say that syft (https://github.com/anchore/syft) generates purls with distro and arch in the query,
in terms of vulnerabilities, I've seen on osv website, many vulnerabilities that are identified to be on specific debian versions. This implied to me that those vulnerabilities are not relevant to similar version and package names but different debian versions. is this the case?
and in regards to arch looking at the specification of purls([link](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst)): 
![image](https://github.com/google/osv.dev/assets/38865738/0e46c505-d2ae-4c88-b29b-84baf70f84e5)
meaning that we probably shouldn't disqualify a search if arch is specified and you saved it a source.

**Comment by oliverchang** [comment]
CC @another-rex who implemented a lot of the Debian matching.

**Comment by another-rex** [comment]
> arch=source is problematic as it automatically disqualifies querying by a specific architecture i.e. x86

It's currently all set to source as we have no mechanism at the moment to identify a DSA vulnerability that only affects a specific architecture, 

> in terms of vulnerabilities, I've seen on the osv website, that many vulnerabilities are identified to be on specific debian versions. This implied to me that those vulnerabilities are not relevant to ones with similar version and package names but different debian versions. is this the case?

Sort of, the specific debian versions/releases listed there are the releases listed by the original DSA/DLA published by Debian.  Debian only publishes advisories for releases that are supported, so older releases might still be vulnerable, but no longer has any support so no advisories are published for them.

> @satanshiro is it fair to say this is more of an issue when trying to search using a purl with the API?
> 
> Ideally you'd like the search for using
> 
> ```
> "package": {
>   "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64"
> }
> ```
> 
> to match vulnerabilities that have `pkg:deb/debian/imagemagick?arch=source`?
> 

Agreed, while this will introduce some false positives for packages that only affect a specific ecosystem, but that's more of a data quality problem. Ideally the "source" arch should be interpreted as matching all archs.

> and
> 
> ```
> "package": {
>   "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?distro=debian-8"
> }
> ```
> 
> to only match vulnerabilities in what is essentially the `Debian:8` ecosystem?

I think this definitely makes sense to implement, only question here is should distro be the release name (as in the PURL spec examples), or just a `debian-<number>`?

**Comment by satanshiro** [comment]
another thing I found out is there is no support for upstream query, which is not in purl spec but is heavily used for cve querying @another-rex 
I think it is also very important for example the purl :
`pkg:deb/debian/libcurl3-gnutls@7.74.0-1.3+b1?&upstream=curl%407.74.0-1.3&distro=debian-11`
actually does have cves when upstream is calculated.
(notice sometimes upstream has a version and sometimes it doesn't)
for the time being I manipulate the purl to actually use the upstream if it exists

**Comment by andrewpollock** [comment]
@satanshiro it'll help greatly if you could distil this down to some concrete examples (think test cases) of purls and what you expect returned from a query that uses them.

**Comment by satanshiro** [comment]
hi! I would like to thank you for your promptly responses, very much appreciate it. I'm sorry for the confusion before hand.
let me elaborate here again on all the cases we have with purls / debian or alpine type osvs .
Firstly our motive to use purls with the osv api is to be able to catch exact vulnerabilities the cannot be found with simply querying a library with it's version and ecosystem.  An important note: we are not sure that this motive is even true as I will explain in the following examples. but please inform me if you already don't agree with this assumption as we plan to have greater investigation.
all purls provided have been extracted using syft.

1) ecosystem versions specified as distro search param in purl is ignored - 
 example : "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?distro=debian-8"
 the distro is ignored
 what do I expect:
I think querying with distro names will cause problems ignoring it is a good option.
why: sometimes the library version includes the distro version in some semantics, also if a cve applies for a specific version of a library it should almost definitely be relevant also for other distros.

2) architecture in the purl as search param returns an empty object in the api
example: "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1?arch=amd64"
will result in {}
and "purl": "pkg:deb/debian/imagemagick@8:6.9.10.23+dfsg-2.1+deb10u1"
will result in the full osv object
what do I expect:
Ignore the architecture - the likelihood of a cve to apply to only specific architectures are very slim, if you have this data and somehow can extract it from the advisories then great but from what I've seen it doesn't exist, returning an empty object is definitely a bug.

3) upstream in search param is ignored:
example: "purl": "pkg:deb/debian/libssl1.1@1.1.1n-0+deb11u1?upstream=openssl"
will result in empty object {}
what do I expect:
well this one is tricky I personally think that a cve in a sub package such as ssl should be considered as part of openssl and return the cve just like querying : "purl": "pkg:deb/debian/openssl@1.1.1n-0+deb11u1" (which returns a full osv object with vulnerabilities) in fact upstream which is not a part of purl spec was created specifically to help query for cves. this is because from what I've seen advisories only reference the main package and not sub packages even if the specific code line was a sub package. please correct me if I'm wrong.
this one is up to you, you can also require developers to manually manipulate a query
4) last but not least is that api queries against alpine do not work at all.
example: "purl":"pkg:apk/alpine/busybox" returns an empty object while
{
    "package": {
        "name": "busybox",
        "ecosystem":"Alpine"
}
returns the full osv object with vulnerabilities
writing in the purl the version and playing with it in other ways did not help me.

what I expect:
for purls on alpine to work I'm not sure what happens in other ecosystems they might suffer from a similar problem.


thanks again for your dedicated work if there's anything I can contribute I will do it happily
have a nice day.

**Comment by another-rex** [comment]
> 4. last but not least is that api queries against alpine do not work at all.
example: "purl":"pkg:apk/alpine/busybox" returns an empty object while

Can you test this again? I think this has been fixed recently. 
```
{
  "package": {
    "purl": "pkg:apk/alpine/busybox"
  }
}
```

**Comment by satanshiro** [comment]
yes! #4 was fixed thank you!

**Comment by andrewpollock** [comment]
@satanshiro thanks for confirming, did you mean to cite this issue?
