### ISSUE TITLE
Alias missing from api

### ISSUE THREAD

**Issue by satanshiro** [google/osv.dev#1461]
I'm not sure when this started but for debian ecosystems when querying against the api we don't get alias array string anymore instead there is a related one.
try `curl --location 'https://api.osv.dev/v1/query' \
--header 'Content-Type: application/json' \
--data-raw '{
    "package": {     
        "purl":"pkg:deb/debian/openssl@1.1.1n-0+deb11u4"
    }
}'`
as far as we know it's missing alias object which used to be there

**Comment by andrewpollock** [comment]
Hi @satanshiro

This change was intentional (see #1381), we've been trying to clarify our use of `alias` versus `related` to better align with the schema, see also https://ossf.github.io/osv-schema/#aliases-field versus https://ossf.github.io/osv-schema/#related-field

Apologies for the inconvenience this one-time churn may have caused.
