### ISSUE TITLE
Not possible to define range with pre release versions

### ISSUE THREAD

**Issue by rtfpessoa** [google/osv.dev#1738]
**Describe the bug**

Not sure if bug is the best category, but felt like this was useful to be discussed since maybe it is not clear.

If you look at vulnerabilities like [GHSA-wgh7-54f2-x98r](https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-wgh7-54f2-x98r/GHSA-wgh7-54f2-x98r.json), versions like `11.0.0.beta3`, `11.0.0.beta2`, `11.0.0.beta1` or `11.0.0-alpha0` should be marked as affected even though they are not.

This happens since defining a range does not seem possible and the only solution would be to enumerate the versions.

Seems like people are creating bad advisories due to this limitation.
Have you considered introducing a way to overcome this?

**To Reproduce**

Steps to reproduce the behaviour:
1. Check description above

**Expected behaviour**

Maybe allow to define pre-release as part of introduced?
Any other way that avoid people doing it incorrectly.

**Screenshots**

N/A

**Comment by oliverchang** [comment]
Hi!

Pre-release versions are absolutely supported in the OSV schema. The valid versions that can be specified follow the rules of that ecosystem, so there's no reason why a valid pre-release version cannot be used.

For [GHSA-wgh7-54f2-x98r](https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-wgh7-54f2-x98r/GHSA-wgh7-54f2-x98r.json), the "introduced" version is set as "11.0.0", which sorts after all pre-release versions, which is why they are not included. 

If the correct behaviour is to include pre-release versions, then the entry needs to be modified to `"introduced": "11.0.0.beta1"`, which you can suggest to GHSA via a PR.

**Comment by oliverchang** [comment]
See https://github.com/github/advisory-database/blob/a898cc18bb9770f8956f3f520519931e31937f90/advisories/github-reviewed/2021/05/GHSA-p2j5-3f4c-224r/GHSA-p2j5-3f4c-224r.json#L33 as an example that has a pre-release version as part of the introduced. 

Closing this as I don't believe there's anything actionable on the OSV side, but please feel free to comment if you have further questions or concerns!

**Comment by rtfpessoa** [comment]
I see what you mean. I was maybe looking at this from a theoretical point.
In practice using the first pre-release should be enough to overcome this.
