### ISSUE TITLE
Support scanner / analysis for Maven and NPM projects

### ISSUE THREAD

**Issue by cniweb** [google/osv.dev#182]
It would be nice to have a scanner or analysis tool available that scans dependencies of Maven (pom.xml) or NPM (package.json) projects and checks the components against the API.

**Comment by oliverchang** [comment]
Hi! Sorry for the late reply.

Indeed! Once we have Maven and NPM data in our database, we will look at building a universal tool that can scan dependencies in major package ecosystems.

**Comment by G-Rath** [comment]
@oliverchang fwiw I've actually built such a tool ([`osv-detector`](https://github.com/G-Rath/osv-detector)), which has native parsers for most of the lockfiles (except Maven / `pom.xml` for now) and I have plans to support taking in csv to allow you to arbitrarily provide package details.

I originally wrote it for the GH advisory DB as I didn't realise this repo/db was a thing, but now that I do I'm going to look to switching to this via downloading the `all.zip` files for each ecosystem - I'm pretty sure it should mostly work out of the box, since it's using the OSV format already.

**Comment by G-Rath** [comment]
[`v0.3.0`](https://github.com/G-Rath/osv-detector/releases/tag/v0.3.0) switches `osv-detector` over to using these databases.

@cniweb Parsing Maven / `pom.xml` is not yet supported but is planned: https://github.com/G-Rath/osv-detector/issues/33

**Comment by oliverchang** [comment]
Thanks for the work here @G-Rath! This is very useful to consumers of this data.
