### ISSUE TITLE
Possibility to dump DB

### ISSUE THREAD

**Issue by Dimasbelousov** [google/osv.dev#1912]
Hello! I'm quite new to using OSV and I would love to know if there's any chance I could dump the DB, deploy it in my own infra with no access to global network and manually update it by myself (like it's done in NVD DB for OWASP dependency analyzers)

**Comment by RomainLefeuvre** [comment]
Hello, it would be very useful for us too!

https://github.com/google/osv.dev/issues/1897

**Comment by another-rex** [comment]
Thanks for the interest in OSV!

We provide a dump of the DB's data [here](https://google.github.io/osv.dev/data/#data-dumps), without affected commit info (this mostly affects C/C++ libraries).

As for deploying and running the infrastructure locally, it's not possible at the moment because of our reliance on Datastore. See https://github.com/google/osv.dev/issues/546 and https://github.com/google/osv.dev/issues/1124 which are a very similar requests to this one.

There is actually some work being done currently to reduce the reliance on datastore though, but nothing is confirmed yet. Please follow #546 and I'll post an update on that issue when we have more information!

**Comment by andrewpollock** [comment]
To add some more colour, it's _theoretically_ possible to take everything in this GitHub repository and stand up your own instance of the infrastructure in your own Google Cloud project. It's never been tried, and I can confidently say that things aren't optimised for it, but there shouldn't be any intentionally secret sauce that isn't available in this repository. It's very intentionally Open Source for that reason.
