### ISSUE TITLE
Getting a 429 when calling https://google.github.io/osv.dev/post-v1-querybatch/

### ISSUE THREAD

**Issue by jimshowalter** [google/osv.dev#1975]
**Describe the bug**
The calls have been rate-limited, despite what https://google.github.io/osv.dev/faq/#is-the-api-rate-limited says.

I was just trying to finish the unit tests, and after that they won't be run very often.

**To Reproduce**
Steps to reproduce the behaviour:
1. Call the API with a couple hundred dependencies, 10 or 15 times closely together.

**Expected behavior**
The calls shouldn't be rate-limited, or the FAQ needs to be updated (our preference of course would be no rate-limiting).

**Comment by andrewpollock** [comment]
Our FAQ is still accurate with respect to rate limiting, something else is afoot here. Investigating.

**Comment by jimshowalter** [comment]
I'm kicking myself for not taking a screenshot, but I thought it was going to keep happening and I'd get another chance. But it never happened again.

**Comment by andrewpollock** [comment]
@jimshowalter so it was a transient issue and you can no longer reproduce it?

**Comment by jimshowalter** [comment]
Correct.

**Comment by andrewpollock** [comment]
We did further investigation on our end, and could still see evidence of intermittent 429's being served. In the process of debugging further, we resolved the problem (unfortunately without getting to the root cause).

We have made adjustments to our SLO monitoring so 429's are considered problematic, so if the problem reoccurs, our alerting should bring it to our attention.
