### ISSUE TITLE
combine-to-osv doesn't reflect last modified time of component parts

### ISSUE THREAD

**Issue by andrewpollock** [google/osv.dev#2103]
**Describe the bug**
Currently, the `modified` time of an OSV record emitted by `combine-to-osv` reflects the modified time of the underlying CVE record.

This means that if one of the `PackageInfo` parts combined has changed, the resultant OSV record is not routinely re-imported (see also https://github.com/google/osv.dev/blob/master/tools/datafix/reimport_gcs_record.py)

**Expected behaviour**
- When one of the `PackageInfo` part files has changed, the OSV record is re-imported.
- The `modified` field reflects the most recent modification to one of the parts that compromise the OSV record

**Additional context**
One possible solution is for https://github.com/google/osv.dev/blob/216c120c52f7ee7c310aba51cbaa57418b64ed2f/vulnfeeds/cmd/combine-to-osv/main.go#L93-L108 to also return the most recent timestamp of all of the parts files loaded

**Comment by hogo6002** [comment]
Thanks Andrew for recording this issue. 
I just noticed that almost all the Debian part files will be modified each time run. This is because it uses a map to store all Debian releases, so the order is not the same every time when it outputs to the `PackageInfos` file. 
I will need to fix this to avoid unnecessary updating. Also checked other parts output, Alpine doesn't have this issue, but I not sure about nvd (all last modified dates are today).
