### ISSUE TITLE
Data quality issue with GHSA-4wrc-f8pq-fpqp

### ISSUE THREAD

**Issue by wrngrn** [google/osv.dev#2197]
**The CVE ID**
CVE-2016-1000027
https://osv.dev/vulnerability/CVE-2016-1000027
https://osv.dev/vulnerability/GHSA-4wrc-f8pq-fpqp

**Describe the data quality issue observed**

Missing releases
Versions are missing in the affected[].versions field.
All vesions before 6.0.0 are affected but the affected[].versions list ends at 5.3.32 it is missing 5.3.33 and 5.3.34 

Suggested changes to record
Update the affected versions to include all the missing releases.

Additional context
Thanks a lot!

**Comment by andrewpollock** [comment]
Hello,

Thank you for taking the time to report this data quality issue.

Please note that in OSV.dev, [CVE-2016-1000027](https://osv.dev/vulnerability/CVE-2016-1000027) and [GHSA-4wrc-f8pq-fpqp](https://osv.dev/vulnerability/GHSA-4wrc-f8pq-fpqp) are distinct vulnerability records. 

Your feedback relates specifically to the latter record, not the former.

[GHSA-4wrc-f8pq-fpqp](https://osv.dev/vulnerability/GHSA-4wrc-f8pq-fpqp) originates from the GitHub Advisory Database, and can be directly corrected via https://github.com/advisories/GHSA-4wrc-f8pq-fpqp/improve

That said, I see that the source record was corrected in https://github.com/github/advisory-database/commit/2f3ad85ff9e9fa2eac252dd5f980f00bbc73a52d 

Due to #2017 and #2018, subsequent updates to Git-based source records are not picked up by OSV.dev's importer.

**Comment by andrewpollock** [comment]
Reviewing https://osv.dev/vulnerability/GHSA-4wrc-f8pq-fpqp today, I note that the changes from https://github.com/github/advisory-database/commit/2f3ad85ff9e9fa2eac252dd5f980f00bbc73a52d _are_ reflected, so I've clearly misunderstood the nature of the bugs I mentioned previously... We can close this out.
