### ISSUE TITLE
Request for Lowercase ( even Space-Free ) Abbreviation for Query API Eco Name

### ISSUE THREAD

**Issue by edwinjhlee** [google/osv.dev#2300]
## Description:
    
The current query API eco name contains uppercase letters and spaces, making it cumbersome to use in command-line calls.  For improved usability and consistency with other API conventions, we request a lowercase ( even space-free  ) abbreviation for the eco name.
    
## Benefits:
    
Improved Command-Line Usability: A concise abbreviation will make it easier to type and remember when using the API in scripts and command-line tools.

It will be even better if the naming is (partly) consistent with CPE23 standard.

## Example:
    
If the current eco name is "Rocky Linux", a possible abbreviation could be "rockylinux", or even "rocky", or "rocky:linux" (cpe23)
    
##  Request:
    
We kindly request the development team to consider adding a lowercase, space-free abbreviation for the query API eco name. This will significantly enhance the user experience.

**Comment by oliverchang** [comment]
Hi there, thanks for the feature request.

Our current position is this kind of fuzzy matching is best done on the client side. The reasoning is:

- The OSV Schema provides a canonical formatting of ecosystem names, and we'd like to not encourage more ways to diverge from it and reduce the consistency of ecosystem names in the OSV platform. 

- It's unclear how many users this would benefit, since most of our users would likely be using the API in an automated setting (e.g. a vulnerability scanner), rather than users typing on a command line.  

We'll re-assess this if we see more requests from our users for this.
