### ISSUE TITLE
Data quality issue with CVE-2023-34055

### ISSUE THREAD

**Issue by Albertoimpl** [google/osv.dev#2375]
**The CVE ID**
https://nvd.nist.gov/vuln/detail/CVE-2023-34055

**Describe the data quality issue observed**
Starting some days ago this CVE stopped being reported.

**Additional context**
For example, `org.springframework.boot:spring-boot:3.1.4` should be reported with this CVE.

**Comment by andrewpollock** [comment]
Looking at the source NVD data:

```
{
  "configurations": [
    {
      "nodes": [
        {
          "operator": "OR",
          "negate": false,
          "cpeMatch": [
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:vmware:spring_boot:*:*:*:*:*:*:*:*",
              "versionStartIncluding": "2.7.0",
              "versionEndIncluding": "2.7.17",
              "matchCriteriaId": "6706E7D6-A20F-4BEF-9A2D-65C60C32D3A0"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:vmware:spring_boot:*:*:*:*:*:*:*:*",
              "versionStartIncluding": "3.0.0",
              "versionEndIncluding": "3.0.12",
              "matchCriteriaId": "9C09D8C7-323F-4EA7-9B2A-7F7278108930"
            },
            {
              "vulnerable": true,
              "criteria": "cpe:2.3:a:vmware:spring_boot:*:*:*:*:*:*:*:*",
              "versionStartIncluding": "3.1.0",
              "versionEndIncluding": "3.1.5",
              "matchCriteriaId": "A08E05A3-BA33-4797-976D-537BB0AE4D6B"
            }
          ]
        }
      ]
    }
  ]
}
```

Looking at the conversion treatment (for the `3.1.0` to `3.1.5` range in particular):

```
[CVE-2023-34055]: Attempting version resolution for {Introduced:3.1.0 Fixed: LastAffected:3.1.5} using "https://github.com/spring-projects/spring-boot"
[CVE-2023-34055]: Successfully derived {Repo:https://github.com/spring-projects/spring-boot Introduced:0fc23d24912c698608a5ca02fdadbae60cee9a74 Fixed: Limit: LastAffected:} for introduced version "3.1.0"
[CVE-2023-34055]: Successfully derived {Repo:https://github.com/spring-projects/spring-boot Introduced: Fixed: Limit: LastAffected:b2663ab76ae151f51c411ebc6ba8a3904517a5bf} for last_affected  version "3.1.5"
```

Resulting in:

```
"affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "repo": "https://github.com/spring-projects/spring-boot",
          "events": [
            {
              "introduced": "0fc23d24912c698608a5ca02fdadbae60cee9a74"
            },
            {
              "last_affected": "b2663ab76ae151f51c411ebc6ba8a3904517a5bf"
            }
          ]
        }
      ]
    }
  ]
```

This seems all correct, as expected.

Manually rerunning analysis of this record does not appear to produce any version ranges, though:

```
INFO:root:Analyzing /tmp/CVE-2023-34055.json
INFO:root:Cloning https://github.com/spring-projects/spring-boot to /tmp/tmpy_u935s5
INFO:root:No changes required.
```

In theory that should have matched some tags though:

```
$ git ls-remote -t https://github.com/spring-projects/spring-boot | fgrep "3.1.0
> 3.1.1
> 3.1.2
> 3.1.3
> 3.1.4
> 3.1.5"
5dad886e3c44fd3d80c5062c47dde20d74d11fe0        refs/tags/v3.1.0
0fc23d24912c698608a5ca02fdadbae60cee9a74        refs/tags/v3.1.0^{}
8cf4274f48d370ae3fdef653d8a3ae9742902784        refs/tags/v3.1.0-M1
ee1c40c17b63f3cdfd39c00452c7b9c17b63b0ea        refs/tags/v3.1.0-M1^{}
7e0d413a803b17c654da0f88915f2c52d9492506        refs/tags/v3.1.0-M2
b39717baa3111622491d9760d8df4ed54186b67f        refs/tags/v3.1.0-M2^{}
657a1c765f78bfbb0c89f413f69bc4566047bf9f        refs/tags/v3.1.0-RC1
361e47b71e2fd9297cbc6f9041dc76a49707231a        refs/tags/v3.1.0-RC1^{}
152156105161e9de3894c37f4f7d25605f457c97        refs/tags/v3.1.0-RC2
ef69a7d7617a3949ac31ffc6133ace0f8fbd7752        refs/tags/v3.1.0-RC2^{}
47e1c8378d3215f1d7391309aa2a354caab9bf0d        refs/tags/v3.1.1
ae50fa6c70bbfa6871632c1d5f63fc255af6c500        refs/tags/v3.1.1^{}
b36f531ac2d30fab4b302b91c109319561ddb645        refs/tags/v3.1.10
2a1a57b93d27801bbf7c9d3af80fc0214b413c15        refs/tags/v3.1.10^{}
f10490337a581ec17e8b0d1eb0ed74573d1422a0        refs/tags/v3.1.11
36a152b9da293cfd34767b6d25ec7a719c4711b2        refs/tags/v3.1.12
0f0fb455168072aa559264fbc48192189d39ac6c        refs/tags/v3.1.2
b9177e5786e9908aae3948f5c6ca76dccfe292ee        refs/tags/v3.1.2^{}
c5433723205dd9da63a57c802e18a3fc9775ba4b        refs/tags/v3.1.3
9edc7723129ae3c56db332691c0d1d49db7d32d0        refs/tags/v3.1.3^{}
2b944c93bac8b72804b11fc1324445ee44fba033        refs/tags/v3.1.4
3ed1f1a064a10e53adc2ad8c0b46a4b2c148ee21        refs/tags/v3.1.4^{}
d59bf2c08b64d7542b28bcefd0a48e162a14cb27        refs/tags/v3.1.5
b2663ab76ae151f51c411ebc6ba8a3904517a5bf        refs/tags/v3.1.5^{}
```

So I'll have to dig into why it did not.

**Comment by andrewpollock** [comment]
Furthermore:

```
$ git ls-remote -t https://github.com/spring-projects/spring-boot | grep b2663ab76ae151f51c411ebc6ba8a3904517a5bf
b2663ab76ae151f51c411ebc6ba8a3904517a5bf        refs/tags/v3.1.5^{}
```

Yet https://github.com/spring-projects/spring-boot/commit/b2663ab76ae151f51c411ebc6ba8a3904517a5bf is giving us the good old "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." and sure enough:

```
$ git clone -q https://github.com/spring-projects/spring-boot
$ git -C spring-boot/ branch -r --contains b2663ab76ae151f51c411ebc6ba8a3904517a5bf
```

So our analysis is legitimately failing because this commit can (no longer?) be found in the repository...

**Comment by andrewpollock** [comment]
Hi @Albertoimpl 

> Starting some days ago this CVE stopped being reported

Could you elaborate on what you mean by this? As best I can determine nothing about this record has changed recently. Was it being reported when scanning by commits, or as GHSA-jjfh-589g-3hjx when scanning by package and version?

**Comment by Albertoimpl** [comment]
Hi @andrewpollock
Thanks a lot for taking a look.

It's the second case, normally we download https://osv-vulnerabilities.storage.googleapis.com/Maven/all.zip reindex and filter it ourselves.
If I look at the count of CVEs we were processing two weeks ago, we had about 90492, and this week 89827.

**Comment by andrewpollock** [comment]
@Albertoimpl for [CVE-2023-34055](https://api.osv.dev/v1/vulns/CVE-2023-34055) in particular, this would never have matched by package and version, because being converted from the NVD, it is going to have commit hashes only.

If you are instead referring to [GHSA-jjfh-589g-3hjx](https://api.osv.dev/v1/vulns/GHSA-jjfh-589g-3hjx), looking at the [history on the source record](https://github.com/github/advisory-database/commits/main/advisories/github-reviewed/2023/11/GHSA-jjfh-589g-3hjx/GHSA-jjfh-589g-3hjx.json), I can see that:

- it was [initially published](https://github.com/github/advisory-database/commit/4004895155db3ce3dce1cb9b33c0722e8af7f925#diff-8b76fa5847cd568708218ddf722c0a55521e5b8dda4c9249c5545002df46a058) including `org.springframework.boot:spring-boot`
- the package name changed from `org.springframework.boot:spring-boot` to `org.springframework.boot:spring-boot-actuator` in [this update](https://github.com/github/advisory-database/commit/adf108ed87cfbe666a56cd9cab986afc3854150e)

So this aligns with what you initially reported about `org.springframework.boot:spring-boot`.

That said, looking at the description of the vulnerability, the record in its current form seems accurate. Why do you feel it is not?

For future reference, it's really important to be accurate about the record you're reporting feedback on. 

I spent quite a bit of time looking at the wrong record, because you referred to [CVE-2023-34055](https://api.osv.dev/v1/vulns/CVE-2023-34055) instead of [GHSA-jjfh-589g-3hjx](https://api.osv.dev/v1/vulns/GHSA-jjfh-589g-3hjx). In this case, the [FAQ](https://google.github.io/osv.dev/faq/#ive-found-something-wrong-with-the-data) entry applies.

> If I look at the count of CVEs we were processing two weeks ago, we had about 90492, and this week 89827.

I think it's also important to be clear here: are you referring to exported OSV records for the Maven ecosystem with a `CVE` prefix specifically, or exported OSV records for the Maven ecosystem in general? (Given that `gs://osv-vulnerabilities/Maven/all.zip` appears to currently contain 4,992 records, I'm not entirely clear on what set of records you're downloading). It doesn't seem abnormal for there to be some churn in record count on a daily basis as records are corrected and/or withdrawn. If records are completely _disappearing_, then that seems like something to dig into further.

Given I don't believe there's any further action required here, I'm going to close this. Feel free to reopen with more details if you feel differently. If you have any feedback on the user experience or your user journey that would help streamline future feedback for other users in your situation, please also let us know.

**Comment by Albertoimpl** [comment]
Hi @andrewpollock,
I truly apologize for the confusion, you are very right. I did not realize the record moved from `spring-boot` to `spring-boot-actuator` and wrongly reported it as a data quality issue here when I should have not.
I will definitely take a better look next time and thank you very much for clearly explaining the process you follow. No further action is required.
