### ISSUE TITLE
Data quality issue with PYSEC-2024-60

### ISSUE THREAD

**Issue by woodruffw** [google/osv.dev#2390]
Hi there,

I'm reporting a data quality issue with PYSEC-2024-60. You can see OSV's copy of the ID here:

https://osv.dev/vulnerability/PYSEC-2024-60

**Describe the data quality issue observed**

There are multiple issues with this report:

* The fix version (`3.7`) is not listed
* The `git` introduced ref is invalid (`0`)

**Suggested changes to record**

* The Python ecosystem fix version should be `3.7`
* The `git` introduced ref should be https://github.com/kjd/idna/commit/e9b1c9202908745fff22e9e4bf3d7bb7d6f6c6f5 (this is not exactly precise, but the `git` history doesn't immediately distinguish between the `0.1` and `0.2` release events so the initial commit for the repo seems most appropriate).

**Additional context**

This was observed downstream in PYSEC as https://github.com/pypa/advisory-database/issues/185 and fixed with https://github.com/pypa/advisory-database/pull/186.

**Comment by andrewpollock** [comment]
Hi @woodruffw 

The problem is that https://github.com/pypa/advisory-database/pull/186 creates an invalid record, so it's not being imported successfully. See https://github.com/pypa/advisory-database/pull/186/files#r1677256957 for what needs to be corrected. See https://ossf.github.io/osv-schema/#requirements

You're on the correct path with making the record corrections at the record source, if you'd like to also modify the `introduced` commit hash, you can make that change there and it will flow through. There is nothing invalid about `0`, see https://ossf.github.io/osv-schema/#special-values
