### ISSUE TITLE
DSA-5649-1 missing in OSV.dev

### ISSUE THREAD

**Issue by RamvigneshPasupathy** [google/osv.dev#2471]
DSA-5649-1 missing in OSV.dev - https://osv.dev/list?q=DSA-5649-1&ecosystem=Debian

Any specific reason for this? Or is it missed because of some bug in the debian to osv conversion script? 🤔 

![image](https://github.com/user-attachments/assets/09670343-45c0-4404-ac6c-30e6e9ef1dc0)

Debian References for the same DSA are available

- Debian Security Tracker repo [link](https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/406a95fce428ed893fd70ae101cbe0bc1bb8c80a/data/DSA/list#L353)
- DSA Mail Announcement [link](https://lists.debian.org/debian-security-announce/2024/msg00057.html)

**Comment by oliverchang** [comment]
@hogo6002 can you please take a look?

**Comment by hogo6002** [comment]
DSA-5649-1 doesn't have any affected versions info, so we skipped this one. https://security-tracker.debian.org/tracker/DSA-5649-1

**Comment by hogo6002** [comment]
We also don't have its Debian security tracker information in our database (https://osv.dev/vulnerability/CVE-2024-3094) because this vuln doesn't affect any stable Debian release. For the Debian unstable release, the vulnerability has `not yet assigned` as its urgency level, and we don't include vulnerabilities with that tag in our OSV.
`"CVE-2024-3094":{"description":"....","scope":"local","releases":{"bookworm":{"status":"resolved","repositories":{"bookworm":"5.4.1-0.2"},"fixed_version":"0","urgency":"unimportant"},"bullseye":{"status":"resolved","repositories":{"bullseye":"5.2.5-2.1~deb11u1","bullseye-security":"5.2.5-2.1~deb11u1"},"fixed_version":"0","urgency":"unimportant"},"sid":{"status":"resolved","repositories":{"sid":"5.6.2-2"},"fixed_version":"5.6.1+really5.4.5-1","urgency":"not yet assigned"},"trixie":{"status":"resolved","repositories":{"trixie":"5.6.2-2"},"fixed_version":"5.6.1+really5.4.5-1","urgency":"not yet assigned"}}}}`

**Comment by oliverchang** [comment]
Thanks for investigating! I wonder if we need to ask the upstream Debian Security Tracker maintainers about this particular case?

**Comment by hogo6002** [comment]
> Thanks for investigating! I wonder if we need to ask the upstream Debian Security Tracker maintainers about this particular case?

Yeah, I do see some cases where the urgency tag remains `not yet assigned` and never changes. I will send them an email to ask this type of cases.

**Comment by hogo6002** [comment]
I will close this issue as the DSA behaviour is as expected. 
For Debian Security Tracker issues, track here (https://github.com/google/osv.dev/issues/2482)
