### ISSUE TITLE
Rust package being reported on wrong crates.io entry due to package name reuse

### ISSUE THREAD

**Issue by rhalar** [google/osv.dev#2737]
**Describe the bug**
I've erroneously reported this to
https://github.com/github/advisory-database/issues/4902

but I think this is a more appropriate place for it. I'll copy the issue here:

So looking at https://osv.dev/vulnerability/GHSA-hw4v-5x4h-c3xm
it seems to point to a vulnerability in https://github.com/paritytech/frontier

However, when looking at
https://crates.io/crates/frontier

This does not seem to be the package in question, but rather
https://github.com/peterc-s/frontier

I have an older entry of the crates.io database dump, which does confirm that at one point pkg:crates.io/frontier did really point to the vulnerable package. It seems it has since been removed and the name claimed by a different author.
I'm not sure what the policy for this would be but I'm guessing it would potentially need to be withdrawn? In which case all of these display the same issue

https://github.com/advisories/GHSA-fcmm-54jp-7vf6
https://github.com/advisories/GHSA-v57h-6hmh-g2p4
https://github.com/advisories/GHSA-mjvm-mhgc-q4gp
https://github.com/advisories/GHSA-cjg2-2fjg-fph4
https://github.com/advisories/GHSA-vj62-g63v-f8mf
https://github.com/advisories/GHSA-hw4v-5x4h-c3xm

**To Reproduce**
N/A

**Expected behaviour**
I expect these would have to be withdrawn since the package is no longer available?

**Comment by michaelkedar** [comment]
The description of some of these seem to refer to [`pallet-ethereum`](https://crates.io/crates/pallet-ethereum) and [`pallet-evm`](https://crates.io/crates/pallet-evm), [which](https://github.com/polkadot-evm/frontier/blob/master/frame/ethereum/Cargo.toml) [both](https://github.com/polkadot-evm/frontier/blob/master/frame/evm/Cargo.toml) seem to come from that frontier repository.
I think the GHSA records need to be changed to point to the actual crates.

> I have an older entry of the crates.io database dump, which does confirm that at one point pkg:crates.io/frontier did really point to the vulnerable package. It seems it has since been removed and the name claimed by a different author.

This seems very strange - the [crates.io policies](https://crates.io/policies) suggests that crates should practically never be deleted. I'm not sure how this happened.

**Comment by rhalar** [comment]
I also wasn't aware this is a possibility, the dump I am looking at dates to `2023-07-19`. I have a couple more later ones from the same period but I haven't looked when the change happened.
The name is identical, but the crate ID is different though (`215535` vs `1170076`). And the older ID does not appear in newer dumps at all.

Interestingly enough, `pallet-ethereum` has `215536` as the ID.

**Comment by michaelkedar** [comment]
Right now, I believe this issue is best resolved on the GHSA side.
The OSV records that GHSA are publishing use `{"ecosystem": "crates.io", "name": "frontier"}` as the affected package. Since the actual affected package isn't on crates.io (anymore), GHSA needs to correct the records.

In my opinion, they could do one (or both) of the following:
- Change the affected packages to the corresponding `pallet-*` crates (that do exist) that the vulnerabilities actually impact.
- Change the records to refer directly to the [git repository](https://ossf.github.io/osv-schema/#affectedrangesrepo-field), using `GIT` affected ranges.

I don't think we should mark them as withdrawn, since the vulnerabilities do still actually exist.

@rhalar If you could (re-)open the issue on GHSA (or directly submit the corrections for these records), that would be greatly appreciated.

As for the changing crates issue, there's not much on our end we can do about that. If an OSV record becomes no longer valid, it's mostly up to the source of the record to correct it.

**Comment by rhalar** [comment]
@michaelkedar Thanks for the feedback. I'm not sure why I thought to open the issue here; I think I erroneously thought GHSA OSV entries were published by OSV instead of GHSA directly.

Reopening the issue there.
