### ISSUE TITLE
Move scanner to https://github.com/google/osv-scanner

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#821]
To make releasing/tagging clearer and easier.

**Comment by oliverchang** [comment]
@G-Rath FYI!

**Comment by G-Rath** [comment]
I was just thinking about this - I quite like the setup I have going in `osv-detector` (`goreleaser` + a few other things for linting) so am happy if you want to just lift that (I expect it'll work straight out of the box).

Let me know if you'd like me to help with any part of that too.

**Comment by G-Rath** [comment]
@oliverchang having thought about it more, if you're planning to move the scanner into its own repo I wonder if it might actually be better to start from `osv-detector` as a base instead (either with its existing remote and renaming, or hard-forking) because its already setup with linting, release publishing, CI workflows, extensive tests, etc, has the features we've already talked about pulling into the scanner (config with the ability to ignore stuff, custom databases, using the api and/or downloading the dbs, improved output, etc) - the only things I think are missing that the scanner has is `.git` and sbom support, and recursing into directories.

I'm happy to give you the codebase unlicensed or however you need it if you want so that you can chop it up as much as you like - up to you :)

**Comment by oliverchang** [comment]
Hey @G-Rath, we'd still very much prefer our own `osv-scanner` and moving our own CI processes tools etc there, given that's what our team of 4 is most familiar with. 

I agree there's still the missing pieces that you mentioned, but this is a work in progress so let's continue to iterate to make it the best scanner possible :)

**Comment by oliverchang** [comment]
This is done by @another-rex !
